"""Added review_text to Review Model

Revision ID: 81b0e2bd972a
Revises: efc8b39a9877
Create Date: 2025-04-14 19:53:43.229581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b0e2bd972a'
down_revision = 'efc8b39a9877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_text', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('review_text')

    # ### end Alembic commands ###
